source 'https://github.com/ipapamagic/IPaPods.git'

use_frameworks!
platform:ios,'10.3'
target 'IPaStoreKit_Example' do
    pod 'IPaStoreKit', :path => '../'
#pod 'TPInAppReceipt'#, :path => '~/Downloads/TPInAppReceipt-master'
#pod 'GRKOpenSSLFramework'
end
